export const MEDICAL_FORM_WIDGET_URI = "ui://widget/health-vault-medical-form.html";

export const MEDICAL_FORM_WIDGET_HTML = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;padding:12px;background:transparent;color:#202528}.card{overflow:hidden;border:1px solid #e2e5e7;border-radius:14px;background:#fff}.hero{padding:18px 20px;color:#f7fafc;background:#17213a;border-bottom:3px solid #0b8063}.eyebrow{margin:0 0 6px;color:#9ee3cf;font-size:10px;font-weight:750;letter-spacing:.12em;text-transform:uppercase}h1{margin:0;font-size:21px}.hero p:last-child{margin:7px 0 0;color:#cbd5e1;font-size:12px;line-height:1.45}.body{display:grid;gap:10px;padding:16px 18px}.form,.question,.prefill{padding:13px 14px;border:1px solid #e2e5e7;border-radius:10px}.top,.progress-label{display:flex;justify-content:space-between;gap:12px}.title{font-weight:750}.status{color:#0b8063;font-size:11px;font-weight:700;text-transform:capitalize}.status.not_started{color:#687075}.description,.meta{margin:5px 0 0;color:#687075;font-size:12px;line-height:1.4}.actions{display:flex;flex-wrap:wrap;gap:9px;margin-top:11px;align-items:center}.upload{padding:14px;border:1px dashed #93a3b8;border-radius:10px;background:#f8fafc}.footer{display:flex;justify-content:space-between;gap:12px;padding:0 18px 16px}.link,button{min-height:44px;border:0;background:none;color:#2563eb;font:inherit;font-size:12px;font-weight:750;text-decoration:none;cursor:pointer}.primary{padding:0 16px;border-radius:9px;background:#2563eb;color:white}.secondary{padding:0 14px;border:1px solid #cbd5e1;border-radius:9px}.link:focus-visible,button:focus-visible{outline:3px solid #93c5fd;outline-offset:2px}.bar{height:8px;margin:8px 0 3px;overflow:hidden;border-radius:999px;background:#e5e7eb}.fill{height:100%;background:#0b8063}.question{border-color:#bfdbfe;background:#eff6ff}.question-label{margin:5px 0 0;font-size:15px;font-weight:700}.option{display:inline-block;margin:7px 5px 0 0;padding:5px 8px;border-radius:999px;background:#fff;color:#475569;font-size:11px}.prefill ul{margin:8px 0 0;padding-left:18px}.prefill li{margin:5px 0;color:#475569;font-size:12px}.notice{padding:10px 12px;border-radius:9px;background:#f8fafc;color:#475569;font-size:11px;line-height:1.45}@media(prefers-color-scheme:dark){body{color:#eef1f3}.card,.form,.prefill{border-color:#343a3e;background:#15191c}.upload,.notice{border-color:#56616b;background:#11161a}.description,.meta,.prefill li{color:#a7afb4}.question{border-color:#24598c;background:#10263c}.option{background:#17213a;color:#dbeafe}.link,button{color:#8ab4ff}.primary{color:white;background:#2563eb}.secondary{border-color:#475569}.bar{background:#343a3e}}</style></head><body><main id="app" class="card"><div class="body">Loading medical forms…</div></main><script>
const esc=(v)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const outputOf=(result)=>result?.structuredContent||result||{};
let interactiveOutput=null;
const external=(href)=>window.openai?.openExternal?window.openai.openExternal({href}):window.open(href,'_blank','noopener,noreferrer');
const setBusy=(button,text)=>{button.disabled=true;button.textContent=text};
async function call(name,args,button,label){try{if(button)setBusy(button,label);const result=await window.openai.callTool(name,args);interactiveOutput=outputOf(result);renderOutput(interactiveOutput)}catch(error){showError(error?.message||'Unable to continue.')}finally{if(button)button.disabled=false}}
function showError(message){document.getElementById('app').insertAdjacentHTML('beforeend','<div class="body"><div class="notice" role="alert">'+esc(message)+'</div></div>')}
function renderCatalog(out){const forms=out.forms||[];document.getElementById('app').innerHTML='<div class="hero"><p class="eyebrow">Health Vault</p><h1>Which form do you need?</h1><p>Complete reusable forms with ChatGPT. Uploads and restricted legal fields stay in your secure Vault.</p></div><div class="body">'+forms.map((form)=>'<article class="form"><div class="top"><span class="title">'+esc(form.title)+'</span><span class="status '+esc(form.status)+'">'+esc(form.status.replaceAll('_',' '))+'</span></div><p class="description">'+esc(form.description)+'</p><p class="meta">'+(form.chatEditable?'ChatGPT can prefill safe profile details and ask for what is missing.':'Requires secure web completion.')+(form.updatedAt?' · Updated '+esc(new Date(form.updatedAt).toLocaleDateString()):'')+'</p><div class="actions">'+(form.chatEditable?'<button class="primary" data-start="'+esc(form.id)+'">'+(form.status==='not_started'?'Start in ChatGPT':'Continue in ChatGPT')+'</button>':'<button class="secondary" data-external="'+esc(form.resumeUrl)+'">Open secure form</button>')+'</div></article>').join('')+'<article class="upload"><span class="title">Have a provider form?</span><p class="description">Upload a PDF or clear photos in your private Health Vault. Restricted fields are never collected in chat.</p><div class="actions"><button class="secondary" data-external="'+esc(out.uploadUrl)+'">Upload PDF or photos</button></div></article></div><div class="footer"><span class="meta">'+esc(out.completedCount)+' of '+esc(forms.length)+' common forms complete</span><button class="link" data-external="'+esc(out.allFormsUrl)+'">View all forms</button></div>';
document.querySelectorAll('[data-start]').forEach((button)=>button.addEventListener('click',()=>call('get_medical_form',{templateId:button.dataset.start},button,'Loading…')));document.querySelectorAll('[data-external]').forEach((button)=>button.addEventListener('click',()=>external(button.dataset.external)))}
function promptFor(form,mode){const p=form.progress||{};const q=form.nextQuestion;const intro='Continue my Health Vault '+form.definition.title+' interview in ChatGPT. '+p.readyFields+' of '+p.totalFields+' safe fields are ready ('+p.percentReady+'%). ';if(mode==='review')return intro+'Review the profile-derived suggestions with me, clearly label them as unconfirmed, then ask for corrections. Never ask for SSN, signatures, legal consent, or payment information.';return intro+(q?'Ask me only the next missing question: "'+q.label+'". After my answer, state the updated progress and continue one logical question at a time.':'Review the prefilled suggestions, then prepare the complete safe answer set for confirmation. Never ask for SSN, signatures, legal consent, or payment information.')}
async function continueChat(form,mode,button){try{setBusy(button,'Opening question…');if(!window.openai?.sendFollowUpMessage)throw new Error('Continue by telling ChatGPT you want to finish this form.');await window.openai.sendFollowUpMessage({prompt:promptFor(form,mode)})}catch(error){showError(error?.message||'Unable to start the interview.')}finally{button.disabled=false;button.textContent=mode==='review'?'Review prefilled answers':'Continue interview'}}
function renderForm(form){const d=form.definition,p=form.progress||{},q=form.nextQuestion,s=form.suggestionsToReview||[];document.getElementById('app').innerHTML='<div class="hero"><p class="eyebrow">Health Vault · Form interview</p><h1>'+esc(d.title)+'</h1><p>'+esc(d.description)+'</p></div><div class="body"><div><div class="progress-label"><span class="title">'+esc(p.readyFields)+' of '+esc(p.totalFields)+' fields ready</span><span class="status">'+esc(p.percentReady)+'%</span></div><div class="bar" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+esc(p.percentReady)+'"><div class="fill" style="width:'+esc(p.percentReady)+'%"></div></div><p class="meta">'+esc(p.savedFields)+' saved · '+esc(p.suggestedFields)+' safely prefilled for review · '+esc(p.remainingFields)+' questions remaining</p></div>'+(q?'<section class="question"><p class="eyebrow">Next question</p><p class="question-label">'+esc(q.label)+'</p>'+(q.options||[]).map((option)=>'<span class="option">'+esc(option)+'</span>').join('')+'<div class="actions"><button class="primary" id="continue">Answer in chat</button></div></section>':'<div class="notice">All safe fields are ready. Review profile-derived answers before saving the draft.</div>')+(s.length?'<section class="prefill"><span class="title">Prefilled from your Health Vault profile</span><p class="description">These are suggestions only and must be reviewed before saving.</p><ul>'+s.slice(0,5).map((item)=>'<li><strong>'+esc(item.label)+':</strong> '+esc(item.value)+'</li>').join('')+(s.length>5?'<li>+'+esc(s.length-5)+' more profile suggestions</li>':'')+'</ul><div class="actions"><button class="secondary" id="review">Review prefilled answers</button></div></section>':'')+'<div class="notice">For your privacy, ChatGPT will not request Social Security numbers, signatures, legal consent, or payment information.</div><div class="actions"><button class="link" id="back">← Choose another form</button></div></div>';
const cont=document.getElementById('continue');if(cont)cont.addEventListener('click',()=>continueChat(form,'continue',cont));const review=document.getElementById('review');if(review)review.addEventListener('click',()=>continueChat(form,'review',review));document.getElementById('back').addEventListener('click',(event)=>call('list_medical_forms',{},event.currentTarget,'Loading…'))}
function renderOutput(out){if(out.form)renderForm(out.form);else if(out.forms)renderCatalog(out)}function render(){renderOutput(interactiveOutput||window.openai?.toolOutput||{})}window.addEventListener('openai:set_globals',render);render();
</script></body></html>`;
