export const MEDICAL_FORM_SHARE_WIDGET_URI = "ui://widget/health-vault-medical-form-share-v4.html";

export const MEDICAL_FORM_SHARE_WIDGET_HTML = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box}body{margin:0;padding:14px;font:14px/1.45 ui-sans-serif,system-ui;color:#17223b}.card{border:1px solid #dfe3e8;border-radius:18px;padding:18px}.eyebrow{font-size:11px;letter-spacing:.14em;color:#08785f;font-weight:800}.title{font-size:22px;font-weight:800;margin:4px 0}.review{display:grid;grid-template-columns:minmax(120px,auto) 1fr;gap:8px 16px;border-top:1px solid #e4e7ec;border-bottom:1px solid #e4e7ec;padding:14px 0;margin:14px 0}.label{color:#667085;font-weight:700}.value{overflow-wrap:anywhere}.well{background:#f2f6f7;border-radius:12px;padding:14px;margin:14px 0}.muted{color:#667085}.button{width:100%;border:0;border-radius:12px;padding:13px;background:#17223b;color:#fff;font-weight:800;cursor:pointer}.link{color:#1467e8;font-weight:750}.success{background:#e9f7f2;color:#075e49;border-radius:12px;padding:14px}
</style></head><body><div id="app"></div><script>
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let busy=false,completedShare=null;
function output(){const raw=window.openai?.toolOutput||{};return raw.share||raw.structuredContent?.share||raw}
function render(){const o=completedShare||output();if(!o.templateId||!o.recipientEmail){document.body.hidden=true;return}document.body.hidden=false;const done=o.confirmationState==='confirmed';const delivery=o.emailDelivery?.recipient;const patientDelivery=o.emailDelivery?.patientCopy;const deliveryText=delivery?(delivery.sent?'Email accepted for delivery to '+esc(o.recipientEmail):'Email delivery failed; copy the secure link instead.'):'Confirming will create the link and email it to '+esc(o.recipientEmail)+'.';const receiptStatus=!o.sendPatientCopy?'No patient receipt requested':patientDelivery?(patientDelivery.sent?'Patient receipt accepted for delivery':'Patient receipt email failed; check the verified profile email'):'Send to the verified Health Vault email';const row=(label,value)=>'<div class="label">'+label+'</div><div class="value">'+esc(value)+'</div>';const review=row('Completed fields',(o.completedFieldCount||13)+' of '+(o.totalFieldCount||13))+row('Recipient',o.recipientName+(o.recipientOrganization?' · '+o.recipientOrganization:''))+row('Recipient email',o.recipientEmail)+row('Access','Secure, read-only link')+row('Expiration',o.expiresInHours+' hours after creation')+(o.note?row('Note',o.note):'')+row('Patient receipt',receiptStatus);document.getElementById('app').innerHTML='<section class="card"><div class="eyebrow">FINAL REVIEW · SECURE MEDICAL FORM</div><div class="title">'+esc(o.templateTitle)+'</div><div class="review">'+review+'</div><div class="well">'+deliveryText+'</div>'+(done?'<div class="success"><strong>Secure share created</strong><br><a id="open" class="link" href="#">Open secure share</a><br><span class="muted">Expires '+esc(o.expiresAt)+'</span></div>':'<button id="confirm" class="button">Confirm & Email Secure Share</button><div id="error"></div>')+'</section>';document.getElementById('confirm')?.addEventListener('click',confirmShare);document.getElementById('open')?.addEventListener('click',e=>{e.preventDefault();if(o.shareUrl)window.openai?.openExternal?.({href:o.shareUrl})})}
async function confirmShare(){if(busy)return;busy=true;const o=output();const b=document.getElementById('confirm');if(b){b.disabled=true;b.textContent='Creating and emailing share…'}try{const r=await window.openai.callTool('create_medical_form_email_share',{templateId:o.templateId,recipientName:o.recipientName,recipientOrganization:o.recipientOrganization||undefined,recipientEmail:o.recipientEmail,expiresInHours:o.expiresInHours||24,note:o.note||undefined,sendPatientCopy:Boolean(o.sendPatientCopy),confirmed:true});const serverError=r?.isError?r?.content?.find(item=>item?.type==='text')?.text:null;if(serverError)throw new Error(serverError);completedShare=r?.structuredContent?.share||r?.share||null;if(!completedShare)throw new Error('Health Vault did not return the secure share.');render()}catch(e){const target=document.getElementById('error');if(target)target.innerHTML='<div class="well" role="alert">'+esc(e?.message||'Unable to create the secure share.')+'</div>';if(b){b.disabled=false;b.textContent='Try again'}}finally{busy=false}}render();window.addEventListener('openai:set_globals',render);
</script></body></html>`;
