export const CLINICAL_IMPORT_WIDGET_URI = "ui://widget/health-vault-record-import-v1.html";

export const CLINICAL_IMPORT_WIDGET_HTML = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;padding:12px;background:transparent;color:#17213a}.card{border:1px solid #dfe4e6;border-radius:16px;background:#fff;overflow:hidden}.head{padding:18px 20px;background:#17213a;color:#fff;border-bottom:3px solid #0b8063}.eyebrow{margin:0 0 6px;color:#9ee3cf;font-size:12px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}h1{margin:0;font-size:22px}.body{padding:18px 20px}.notice{margin:0 0 14px;padding:12px;border-radius:9px;background:#edf6f2;color:#145846;font-weight:700}.summary{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}.pill,.type{padding:5px 9px;border-radius:999px;background:#eef1f3;font-size:12px}.item{padding:13px 0;border-bottom:1px solid #e7eaec}.item:last-child{border-bottom:0}.row{display:flex;align-items:center;justify-content:space-between;gap:10px}.title{font-weight:800}.type{text-transform:capitalize;color:#334155}.meta{margin-top:5px;color:#687075;font-size:12px}.badge{display:inline-block;margin-left:6px;padding:2px 7px;border-radius:999px;background:#fff3cd;color:#7a5100;font-size:11px}.actions{padding:0 20px 20px}button{width:100%;min-height:46px;border:0;border-radius:9px;background:#2563eb;color:#fff;font:inherit;font-weight:800;cursor:pointer}button:disabled{opacity:.65}.error{margin-top:10px;padding:10px;border-radius:8px;background:#fef2f2;color:#991b1b}.success{padding:22px 20px;background:#edf6f2;color:#145846}.mark{display:flex;align-items:center;justify-content:center;width:48px;height:48px;margin-bottom:12px;border-radius:50%;background:#0b8063;color:#fff;font-size:28px;font-weight:900}.success h2{margin:0 0 7px;font-size:21px}.success p{margin:0;line-height:1.45}.detail{margin-top:12px!important;font-weight:700}@media(prefers-color-scheme:dark){body{color:#eef1f3}.card{background:#15191c;border-color:#343a3e}.item{border-color:#343a3e}.pill,.type{background:#252b30}.notice,.success{background:#163b32;color:#c7f2e4}}
</style></head><body><main id="app" class="card"><div class="body">Preparing your records…</div></main><script>
const app=document.getElementById('app');const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let preview=null,busy=false,done=false;
function result(v){return v?.imported||v?.structuredContent?.imported||v?.result?.structuredContent?.imported||v?.toolOutput?.imported}
function success(x){if(done)return;done=true;const n=Number(x?.importedCount??preview?.summary?.new??0),d=Number(x?.duplicateCount??preview?.summary?.duplicates??0);app.innerHTML='<div class="head"><p class="eyebrow">Health Vault · Complete</p><h1>Import complete</h1></div><div class="success" role="status" aria-live="polite"><div class="mark">✓</div><h2>Saved to your Health Vault</h2><p>Your selected health records are now available in Health Vault.</p><p class="detail">'+esc(n)+' record'+(n===1?'':'s')+' added'+(d?' · '+esc(d)+' duplicate'+(d===1?'':'s')+' skipped':'')+'.</p></div>'}
function render(){const out=window.openai?.toolOutput,x=result(out);if(x){success(x);return}if(done)return;preview=out?.preview||preview;if(!preview?.items?.length)return;const s=preview.summary||{};const items=preview.items.map(i=>'<div class="item"><div class="row"><span class="title">'+esc(i.title)+(i.importState==='duplicate'?'<span class="badge">Already saved</span>':'')+'</span><span class="type">'+esc(i.recordType)+'</span></div><div class="meta">'+esc(i.providerName||preview.sourceName)+(i.effectiveDate?' · '+esc(i.effectiveDate):'')+(i.status?' · '+esc(i.status):'')+'</div></div>').join('');app.innerHTML='<div class="head"><p class="eyebrow">Health Vault · Review</p><h1>Review health records</h1></div><div class="body"><p class="notice">Nothing has been added to Health Vault.</p><div class="summary"><span class="pill">'+esc(s.new??preview.items.length)+' new</span><span class="pill">'+esc(s.duplicates??0)+' already saved</span><span class="pill">'+esc(preview.sourceName)+'</span></div>'+items+'</div><div class="actions"><button id="save">Import selected records</button><div id="error"></div></div>';document.getElementById('save')?.addEventListener('click',save)}
async function save(){if(busy||done||!preview?.proposalId)return;busy=true;const b=document.getElementById('save');b.disabled=true;b.textContent='Importing…';try{const r=await window.openai.callTool('confirm_connected_health_records_import',{proposalId:preview.proposalId,confirmed:true});success(result(r)||{})}catch(e){document.getElementById('error').innerHTML='<div class="error" role="alert">'+esc(e?.message||'Unable to import these records. Please try again.')+'</div>';b.disabled=false;b.textContent='Try again'}finally{busy=false}}
window.addEventListener('openai:set_globals',render);render();
</script></body></html>`;
