export const MEDICAL_FORM_SHARE_WIDGET_URI = "ui://widget/health-vault-medical-form-share.html";

export const MEDICAL_FORM_SHARE_WIDGET_HTML = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box}body{margin:0;padding:14px;font:14px/1.45 ui-sans-serif,system-ui;color:#17223b}.card{border:1px solid #dfe3e8;border-radius:18px;padding:18px}.eyebrow{font-size:11px;letter-spacing:.14em;color:#08785f;font-weight:800}.title{font-size:22px;font-weight:800;margin:4px 0}.well{background:#f2f6f7;border-radius:12px;padding:14px;margin:14px 0}.muted{color:#667085}.button{width:100%;border:0;border-radius:12px;padding:13px;background:#17223b;color:#fff;font-weight:800;cursor:pointer}.link{color:#1467e8;font-weight:750}.success{background:#e9f7f2;color:#075e49;border-radius:12px;padding:14px}
</style></head><body><div id="app"></div><script>
const esc=(v)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));let busy=false;
function output(){const raw=window.openai?.toolOutput||{};return raw.share||raw}
function render(){const o=output();const done=o.confirmationState==='confirmed';document.getElementById('app').innerHTML='<section class="card"><div class="eyebrow">SECURE MEDICAL FORM</div><div class="title">'+esc(o.templateTitle||'Medical form')+'</div><div class="muted">For '+esc(o.recipientName||'your recipient')+(o.recipientOrganization?' · '+esc(o.recipientOrganization):'')+'</div><div class="well">Read-only link · Expires in '+esc(o.expiresInHours||'24')+' hour(s)<br>Nothing is sent automatically.</div>'+(done?'<div class="success"><strong>Secure share created</strong><br><a id="open" class="link" href="#">Open secure share</a><br><span class="muted">Expires '+esc(o.expiresAt)+'</span></div>':'<button id="confirm" class="button">Confirm Secure Share</button>')+'</section>';document.getElementById('confirm')?.addEventListener('click',confirmShare);document.getElementById('open')?.addEventListener('click',e=>{e.preventDefault();if(o.shareUrl)window.openai?.openExternal?.({href:o.shareUrl})})}
async function confirmShare(){if(busy)return;busy=true;const o=output();const b=document.getElementById('confirm');if(b)b.textContent='Creating secure share…';try{const r=await window.openai.callTool('create_medical_form_share',{templateId:o.templateId,recipientName:o.recipientName,recipientOrganization:o.recipientOrganization||undefined,expiresInHours:o.expiresInHours||24,note:o.note||undefined,confirmed:true});if(r?.structuredContent)window.openai.toolOutput=r.structuredContent;render()}catch(e){if(b)b.textContent='Try again'}finally{busy=false}}render();window.addEventListener('openai:set_globals',render);
</script></body></html>`;
