export const MEDICAL_FORM_SHARE_WIDGET_URI = "ui://widget/health-vault-medical-form-share.html";

export const MEDICAL_FORM_SHARE_WIDGET_HTML = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box}body{margin:0;padding:14px;font:14px/1.45 ui-sans-serif,system-ui;color:#17223b}.card{border:1px solid #dfe3e8;border-radius:18px;padding:18px}.eyebrow{font-size:11px;letter-spacing:.14em;color:#08785f;font-weight:800}.title{font-size:22px;font-weight:800;margin:4px 0}.well{background:#f2f6f7;border-radius:12px;padding:14px;margin:14px 0}.muted{color:#667085}.button{width:100%;border:0;border-radius:12px;padding:13px;background:#17223b;color:#fff;font-weight:800;cursor:pointer}.link{color:#1467e8;font-weight:750}.success{background:#e9f7f2;color:#075e49;border-radius:12px;padding:14px}
</style></head><body><div id="app"></div><script>
const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let busy=false,completedShare=null;
function output(){const raw=window.openai?.toolOutput||{};return raw.share||raw.structuredContent?.share||raw}
function render(){const o=completedShare||output();if(!o.templateId||!o.recipientEmail){document.body.hidden=true;return}document.body.hidden=false;const done=o.confirmationState==='confirmed';const delivery=o.emailDelivery?.recipient;const deliveryText=delivery?(delivery.sent?'Email accepted for delivery to '+esc(o.recipientEmail):'Email delivery failed; copy the secure link instead.'):'Confirming will create the link and email it to '+esc(o.recipientEmail)+'.';document.getElementById('app').innerHTML='<section class="card"><div class="eyebrow">SECURE MEDICAL FORM</div><div class="title">'+esc(o.templateTitle)+'</div><div class="muted">For '+esc(o.recipientName)+(o.recipientOrganization?' · '+esc(o.recipientOrganization):'')+'<br>'+esc(o.recipientEmail)+'</div><div class="well">Read-only link · Expires in '+esc(o.expiresInHours)+' hour(s)<br>'+deliveryText+(o.sendPatientCopy?'<br>The patient will also receive a receipt.':'')+'</div>'+(done?'<div class="success"><strong>Secure share created</strong><br><a id="open" class="link" href="#">Open secure share</a><br><span class="muted">Expires '+esc(o.expiresAt)+'</span></div>':'<button id="confirm" class="button">Confirm & Email Secure Share</button><div id="error"></div>')+'</section>';document.getElementById('confirm')?.addEventListener('click',confirmShare);document.getElementById('open')?.addEventListener('click',e=>{e.preventDefault();if(o.shareUrl)window.openai?.openExternal?.({href:o.shareUrl})})}
async function confirmShare(){if(busy)return;busy=true;const o=output();const b=document.getElementById('confirm');if(b){b.disabled=true;b.textContent='Creating and emailing share…'}try{const r=await window.openai.callTool('create_medical_form_share',{templateId:o.templateId,recipientName:o.recipientName,recipientOrganization:o.recipientOrganization||undefined,recipientEmail:o.recipientEmail,expiresInHours:o.expiresInHours||24,note:o.note||undefined,sendPatientCopy:Boolean(o.sendPatientCopy),confirmed:true});const serverError=r?.isError?r?.content?.find(item=>item?.type==='text')?.text:null;if(serverError)throw new Error(serverError);completedShare=r?.structuredContent?.share||r?.share||null;if(!completedShare)throw new Error('Health Vault did not return the secure share.');render()}catch(e){const target=document.getElementById('error');if(target)target.innerHTML='<div class="well" role="alert">'+esc(e?.message||'Unable to create the secure share.')+'</div>';if(b){b.disabled=false;b.textContent='Try again'}}finally{busy=false}}render();window.addEventListener('openai:set_globals',render);
</script></body></html>`;
