import type { SupabaseClient } from "@supabase/supabase-js";

export const NOURISHED_REBEL_WIDGET_URI = "ui://health-vault/nourished-rebel.html";

export async function callNourishedRebel(supabase: SupabaseClient, action: string, input: Record<string, unknown> = {}) {
  const { data, error } = await supabase.functions.invoke("wellness-insights", {
    body: { action, productKey: "gpt_app", ...input },
  });
  if (error) throw new Error(`Unable to update Nourished Rebel Insights: ${error.message}`);
  if (data?.error) throw new Error(data.error);
  return data;
}

export const NOURISHED_REBEL_WIDGET_HTML = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
:root{color-scheme:light dark;font-family:ui-sans-serif,system-ui;color:#2f332d;background:#faf9f5}*{box-sizing:border-box}body{margin:0}.card{padding:20px;border:1px solid #d9ddd4;border-radius:18px;background:#fff}.eyebrow{font-size:11px;letter-spacing:.14em;text-transform:uppercase;color:#58765e;font-weight:800}.title{font:700 22px Georgia,serif;margin:7px 0 10px}.copy{line-height:1.55;color:#596057}.progress{height:7px;background:#edf0ea;border-radius:9px;overflow:hidden;margin:14px 0}.bar{height:100%;background:#66856d}.pillars{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.pillar{padding:10px;border-radius:12px;background:#f2f3ef}.pillar b{display:block;text-transform:capitalize}.pillar small{color:#686e65}.actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}button,a{border:1px solid #66856d;border-radius:999px;padding:9px 13px;font-weight:700;background:#66856d;color:#fff;text-decoration:none}.secondary{background:transparent;color:#425648}.note{font-size:11px;color:#777;margin-top:14px}textarea{width:100%;min-height:110px;border:1px solid #ccd2c7;border-radius:12px;padding:11px;font:inherit}.questions button{margin-top:10px}.error{color:#a33;font-size:13px}
</style></head><body><div id="app" class="card"><p class="copy">Loading your wellness insight…</p></div><script>
const app=document.getElementById('app');const result=window.openai?.toolOutput||{};const state=result.state||result.result||result;const keys=['sleep','meal_rhythm','energy_cravings','stress','hydration','movement'];const labels={sleep:'Sleep',meal_rhythm:'Meal rhythm',energy_cravings:'Energy & cravings',stress:'Stress',hydration:'Hydration',movement:'Movement'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function insightMarkup(row){const i=row.insight;return '<div class="eyebrow">Nourished Rebel · Wellness Insights</div><div class="title">Here’s where things stand</div><div class="copy">'+esc(i.snapshot)+'</div><div class="pillars">'+Object.entries(i.pillars).map(([k,p])=>'<div class="pillar"><b>'+esc(k.replace('_',' '))+'</b><small>'+esc(p.status.replaceAll('_',' '))+'</small><div class="copy">'+esc(p.summary)+'</div></div>').join('')+'</div><div class="actions"><a href="https://healthvault.me/?app=wellness&source=chatgpt">Open in Health Vault</a><a class="secondary" href="https://nurishedrebel.com/?utm_source=health_vault_gpt&utm_campaign=nourished_rebel_insights">Visit Nourished Rebel</a></div><div class="note">'+esc(i.disclaimer)+' Booking stays on Nourished Rebel’s site and is not integrated with Health Vault yet.</div>'}
function render(s){if(s.latestInsight){app.innerHTML=insightMarkup(s.latestInsight);return}const n=s.checkIn?.answered_count||0;app.innerHTML='<div class="eyebrow">Nourished Rebel</div><div class="title">'+(n?'Pick up where you left off':'Your wellness insights are waiting')+'</div><div class="copy">Six short questions. Answer what you want; every answer saves.</div><div class="progress"><div class="bar" style="width:'+(n/6*100)+'%"></div></div><div class="actions"><button id="start">'+(s.enrollment?.active?'Continue check-in':'Start check-in')+'</button></div>';document.getElementById('start').onclick=()=>start(s)}
function start(s){const key=keys.find(k=>!s.checkIn?.answers?.[k]&&!s.checkIn?.skipped_questions?.includes(k))||keys[0];app.innerHTML='<div class="eyebrow">'+esc(labels[key])+'</div><div class="title">Tell me what’s true right now</div><div class="questions"><textarea id="answer" placeholder="Share only what you’re comfortable sharing."></textarea><div class="actions"><button id="save">Save & continue</button><button class="secondary" id="skip">Skip</button></div><div id="err" class="error"></div></div>';async function submit(skipped){try{let current=s;if(!current.enrollment?.active){const enrolled=await window.openai.callTool('start_nourished_rebel_check_in',{confirmed:true});current=enrolled?.structuredContent?.state||enrolled?.state||current}const value=document.getElementById('answer').value;if(!skipped&&!value.trim())return;const response=await window.openai.callTool('save_nourished_rebel_check_in_answer',{questionKey:key,answer:skipped?null:value.trim(),skipped,confirmed:true});render(response?.structuredContent?.state||response?.state||response)}catch(e){document.getElementById('err').textContent=e.message||'Unable to save.'}}document.getElementById('save').onclick=()=>submit(false);document.getElementById('skip').onclick=()=>submit(true)}
render(state);
</script></body></html>`;
