/*
  # Create EHR Auth Tokens Table

  Short-lived tokens generated by Health Vault when triggering a Keragon EHR fetch
  for a patient who has not yet connected their EHR provider. The token is embedded
  in an auth_link URL that Keragon includes in a HIPAA-compliant email to the patient.
  The patient clicks the link, lands on /ehr-connect, and completes EHR authorization.

  ## New Tables

  ### ehr_auth_tokens
  - `id` (uuid) — primary key
  - `token` (text, unique) — 32-byte URL-safe random token
  - `user_id` (uuid) — the patient this token belongs to
  - `ehr_source` (text) — EHR system to connect (e.g., "athenahealth")
  - `provider_name` (text) — human-readable provider name shown to patient
  - `expires_at` (timestamptz) — token is invalid after this time (default 72h)
  - `used_at` (timestamptz) — set when the patient completes authorization
  - `created_at` (timestamptz)

  ## Security
  - RLS enabled
  - Patients can only read their own tokens (for completion page validation)
  - Only service role can insert tokens (generated server-side by trigger-ehr-fetch)
*/

CREATE TABLE IF NOT EXISTS ehr_auth_tokens (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token text NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  ehr_source text NOT NULL,
  provider_name text NOT NULL DEFAULT '',
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '72 hours'),
  used_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE ehr_auth_tokens ENABLE ROW LEVEL SECURITY;

-- Patients can read their own tokens (needed to validate the link on /ehr-connect)
CREATE POLICY "Users can read own EHR auth tokens"
  ON ehr_auth_tokens
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

-- Patients can mark their own token as used
CREATE POLICY "Users can update own EHR auth tokens"
  ON ehr_auth_tokens
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Index for fast token lookups (used on every page load of /ehr-connect)
CREATE INDEX IF NOT EXISTS idx_ehr_auth_tokens_token ON ehr_auth_tokens(token);
CREATE INDEX IF NOT EXISTS idx_ehr_auth_tokens_user_id ON ehr_auth_tokens(user_id);
