import { CheckCircle2, FileJson, Loader2, RefreshCw, ShieldAlert } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabase';

interface ClinicalPackage { id: string; source_label: string; source_digest: string; source_batch_digest: string; status: string; created_at: string; organizationPatientNumber: string | null; counts: Record<string, number> }
async function invoke(body: Record<string, unknown>) { const response = await supabase.functions.invoke('provider-admin-api', { body }); if (!response.error) return response.data; let detail = response.data?.error; const context = (response.error as { context?: Response }).context; if (!detail && context) try { const payload = await context.clone().json(); detail = payload?.validationErrors?.map((item: { field: string; message: string }) => `${item.field}: ${item.message}`).join('\n') ?? payload?.error; } catch { /* retain SDK message */ } throw new Error(detail ?? response.error.message); }

export function ClinicalImportPanel({ providerAccountId }: { providerAccountId: string }) {
  const [packages, setPackages] = useState<ClinicalPackage[]>([]); const [fileName, setFileName] = useState(''); const [candidate, setCandidate] = useState<unknown>(null); const [candidateSummary, setCandidateSummary] = useState<{ patients: number; resources: number } | null>(null); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const batches = useMemo(() => Object.values(packages.reduce<Record<string, { digest: string; sourceLabel: string; createdAt: string; packages: ClinicalPackage[]; counts: Record<string, number> }>>((result, item) => { const digest = item.source_batch_digest || item.source_digest; const batch = result[digest] ?? { digest, sourceLabel: item.source_label, createdAt: item.created_at, packages: [], counts: {} }; batch.packages.push(item); for (const [key, value] of Object.entries(item.counts)) batch.counts[key] = (batch.counts[key] ?? 0) + value; result[digest] = batch; return result; }, {})), [packages]);
  const load = useCallback(async () => { setBusy('load'); setError(''); try { const data = await invoke({ action: 'list-clinical-imports', providerAccountId }); setPackages(data?.packages ?? []); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load clinical imports.'); } finally { setBusy(''); } }, [providerAccountId]);
  useEffect(() => { void load(); }, [load]);
  async function choose(file: File) { setError(''); setMessage(''); setFileName(file.name); try { const parsed = JSON.parse(await file.text()) as { schemaVersion?: string; patients?: Array<{ resources?: unknown[] }>; resources?: unknown[] }; const patients = parsed.schemaVersion === 'health_vault_clinical_bulk_json_v1' && Array.isArray(parsed.patients) ? parsed.patients : [{ resources: parsed.resources }]; setCandidate(parsed); setCandidateSummary({ patients: patients.length, resources: patients.reduce((total, patient) => total + (Array.isArray(patient.resources) ? patient.resources.length : 0), 0) }); } catch { setCandidate(null); setCandidateSummary(null); setError('Choose a valid JSON file.'); } }
  async function stage() { if (!candidate) return; setBusy('stage'); setError(''); setMessage(''); try { const raw = JSON.stringify(candidate); const digest = Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(raw)))).map((value) => value.toString(16).padStart(2, '0')).join(''); const data = await invoke({ action: 'stage-clinical-import', providerAccountId, sourceDisplayName: fileName, contentSha256: digest, clinicalPackage: candidate }); setMessage(data.duplicate ? 'This exact upload is already staged.' : `${data.patientCount ?? 1} patient package${data.patientCount === 1 ? '' : 's'} and ${data.resourceCount ?? candidateSummary?.resources ?? 0} resources quarantined. Review the per-patient counts, then validate them.`); setCandidate(null); setCandidateSummary(null); setFileName(''); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to stage clinical packages.'); } finally { setBusy(''); } }
  async function validateBatch(digest: string) { setBusy(digest); setError(''); setMessage(''); try { const data = await invoke({ action: 'validate-clinical-import-batch', providerAccountId, contentSha256: digest }); setMessage(`${data.validatedCount} patient packages validated. Their counts can now appear on the matching patient invitations.`); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to validate the clinical batch.'); } finally { setBusy(''); } }
  return <div><p className="text-sm font-semibold text-indigo-600">Synthetic clinical pilot</p><h1 className="mt-1 text-3xl font-bold">Clinical imports</h1><p className="mt-2 text-content-secondary">Upload one bulk clinical file for many roster patients. Each patient remains a separate package for validation, consent, and eventual release.</p>
    <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><div className="flex gap-3"><ShieldAlert className="h-5 w-5 shrink-0" /><div><strong>Quarantine boundary.</strong><p className="mt-1">Only synthetic health_vault_clinical_bulk_json_v1 files are accepted for bulk upload. Patient attachment remains blocked until identity-safe consent release is implemented.</p></div></div></div>
    <section className="mt-6 rounded-xl border border-stroke-subtle bg-surface-raised p-5"><h2 className="font-semibold">Upload bulk patient data</h2><p className="mt-1 text-sm text-content-secondary">The interactive pilot accepts up to 250 roster patients and 5,000 normalized resources per JSON file. Larger production exports will use private resumable storage and asynchronous processing.</p><label className="mt-4 flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-indigo-300 bg-indigo-50/50 px-5 py-7 text-sm font-semibold text-indigo-700"><FileJson className="h-5 w-5" />{fileName || 'Choose bulk clinical JSON'}<input type="file" accept="application/json,.json" className="sr-only" onChange={(event) => { const file = event.target.files?.[0]; if (file) void choose(file); }} /></label>{candidateSummary && <p className="mt-3 text-sm font-medium text-content-secondary">Ready to stage: {candidateSummary.patients} patients · {candidateSummary.resources} resources</p>}<button disabled={!candidate || busy === 'stage'} onClick={() => void stage()} className="mt-4 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy === 'stage' ? 'Quarantining…' : 'Stage bulk file in quarantine'}</button></section>
    {(error || message) && <div role={error ? 'alert' : 'status'} className={`mt-4 whitespace-pre-wrap rounded-lg border p-3 text-sm ${error ? 'border-red-200 bg-red-50 text-red-700' : 'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{error || message}</div>}
    <section className="mt-6 overflow-hidden rounded-xl border border-stroke-subtle bg-surface-raised"><div className="flex items-center justify-between border-b border-stroke-subtle px-5 py-4"><h2 className="font-semibold">Clinical batch history</h2><button onClick={() => void load()} className="flex items-center gap-2 text-sm font-semibold text-indigo-700"><RefreshCw className={`h-4 w-4 ${busy === 'load' ? 'animate-spin' : ''}`} />Refresh</button></div><div className="divide-y divide-stroke-subtle">{batches.map((batch) => { const quarantined = batch.packages.filter((item) => item.status === 'quarantined').length; return <article key={batch.digest} className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><strong>{batch.sourceLabel}</strong><span className={`rounded-full px-2 py-0.5 text-xs font-semibold ${quarantined === 0 ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-900'}`}>{quarantined === 0 ? 'validated' : 'quarantined'}</span></div><p className="mt-1 text-sm text-content-secondary">{batch.packages.length} patients · {batch.counts.total ?? 0} resources · {batch.counts.labs ?? 0} labs · {batch.counts.medications ?? 0} medications · {batch.counts.vitals ?? 0} vitals</p><p className="mt-1 text-xs text-content-tertiary">Staged {new Date(batch.createdAt).toLocaleString()} · Batch {batch.digest.slice(0, 12)}</p></div>{quarantined > 0 && <button disabled={busy === batch.digest} onClick={() => void validateBatch(batch.digest)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white">{busy === batch.digest ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCircle2 className="h-4 w-4" />}Validate all {quarantined} patient packages</button>}</article>; })}{!batches.length && <p className="p-8 text-center text-sm text-content-secondary">No clinical batches have been staged.</p>}</div></section>
  </div>;
}
