import { Check, Clipboard, ExternalLink, FileUp, KeyRound, Link2, Loader2, RefreshCw, Search, Send, Users } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabase';
import { selectCurrentPatientInvitations } from '../../lib/patient-invitation-lifecycle';

interface Patient { id: string; givenName: string; familyName: string; organizationPatientNumber: string | null; email: string | null }
interface Invitation { id: string; provider_patient_identity_id: string; email: string; status: string; expires_at: string; access_expires_at: string; created_at: string; patient: { given_name: string; family_name: string; organization_patient_number: string | null } | null }
interface DeliveryJob { id: string; recipient_email: string; invitation_count: number; status: 'queued' | 'sent' | 'failed' | 'cancelled'; attempt_count: number; last_error: string | null; created_at: string; sent_at: string | null }

async function invoke(body: Record<string, unknown>) {
  const response = await supabase.functions.invoke('provider-admin-api', { body });
  if (!response.error) return response.data;
  let detail = response.data?.error; const context = (response.error as { context?: Response }).context;
  if (!detail && context) try { detail = (await context.clone().json())?.error; } catch { /* retain SDK message */ }
  throw new Error(detail ?? response.error.message);
}

const PAGE_SIZE = 25;

export function PatientAccessInvitationsPanel({ providerAccountId, onImportPatients }: { providerAccountId: string; onImportPatients: () => void }) {
  const [tab, setTab] = useState<'patients' | 'invited'>('patients');
  const [patients, setPatients] = useState<Patient[]>([]); const [invitations, setInvitations] = useState<Invitation[]>([]); const [deliveryJobs, setDeliveryJobs] = useState<DeliveryJob[]>([]);
  const [selected, setSelected] = useState<Set<string>>(new Set()); const [search, setSearch] = useState(''); const [page, setPage] = useState(1);
  const [code, setCode] = useState(''); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { setBusy('load'); setError(''); try { const data = await invoke({ action: 'list-patient-access-invitations', providerAccountId }); setPatients(data?.patients ?? []); setInvitations(data?.invitations ?? []); setDeliveryJobs(data?.deliveryJobs ?? []); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to load patient access invitations.'); } finally { setBusy(''); } }, [providerAccountId]);
  useEffect(() => { void load(); }, [load]);

  const invitationByPatient = useMemo(() => selectCurrentPatientInvitations(invitations), [invitations]);
  const eligiblePatients = useMemo(() => patients.filter((patient) => { const invitation = invitationByPatient.get(patient.id); return Boolean(patient.email) && (!invitation || !['pending', 'accepted'].includes(invitation.status) || (invitation.status === 'accepted' && new Date(invitation.access_expires_at).getTime() <= Date.now())); }), [patients, invitationByPatient]);
  const eligibleIds = useMemo(() => new Set(eligiblePatients.map((patient) => patient.id)), [eligiblePatients]);
  const filteredPatients = useMemo(() => { const value = search.trim().toLowerCase(); return patients.filter((patient) => !value || `${patient.familyName} ${patient.givenName} ${patient.organizationPatientNumber ?? ''} ${patient.email}`.toLowerCase().includes(value)); }, [patients, search]);
  const filteredInvitations = useMemo(() => { const value = search.trim().toLowerCase(); return invitations.filter((item) => !value || `${item.patient?.family_name ?? ''} ${item.patient?.given_name ?? ''} ${item.patient?.organization_patient_number ?? ''} ${item.email} ${item.status}`.toLowerCase().includes(value)); }, [invitations, search]);
  const activeRows = tab === 'patients' ? filteredPatients : filteredInvitations;
  const totalPages = Math.max(1, Math.ceil(activeRows.length / PAGE_SIZE));
  const visiblePatients = filteredPatients.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  const visibleInvitations = filteredInvitations.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  useEffect(() => { setPage(1); }, [tab, search]);

  async function verify() { if (!/^\d{6}$/.test(code)) { setError('Enter the six-digit authenticator code.'); return; } setBusy('mfa'); const { data } = await supabase.auth.mfa.listFactors(); const factor = data?.totp.find((item) => item.status === 'verified'); if (!factor) { setError('A verified authenticator is required.'); setBusy(''); return; } const { error: verifyError } = await supabase.auth.mfa.challengeAndVerify({ factorId: factor.id, code }); if (verifyError) setError(verifyError.message); else { setCode(''); setError(''); setMessage('Protected actions unlocked for 24 hours.'); } setBusy(''); }
  async function createBulk(inviteAllEligible: boolean) { if (!inviteAllEligible && selected.size === 0) return; setBusy('create'); setError(''); setMessage(''); try { const data = await invoke({ action: 'create-patient-access-invitations', providerAccountId, inviteAllEligible, patientIdentityIds: inviteAllEligible ? undefined : [...selected] }); setMessage(`${data.created} invitation${data.created === 1 ? '' : 's'} created${data.skipped ? `; ${data.skipped} already pending or unavailable` : ''}. ${data.deliveryJobs} deduplicated digest delivery job${data.deliveryJobs === 1 ? '' : 's'} queued. Access activates immediately when each patient accepts.`); setSelected(new Set()); await load(); setTab('invited'); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to create patient invitations.'); } finally { setBusy(''); } }
  async function updateDelivery(action: 'cancel-patient-access-delivery' | 'retry-patient-access-delivery', deliveryJobId: string) { setBusy(deliveryJobId); setError(''); setMessage(''); try { await invoke({ action, providerAccountId, deliveryJobId }); setMessage(action.startsWith('cancel') ? 'Delivery job cancelled.' : 'Delivery job returned to the queue.'); await load(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to update delivery job.'); } finally { setBusy(''); } }
  function toggle(id: string) { setSelected((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; }); }
  function togglePage() { const ids = visiblePatients.filter((patient) => eligibleIds.has(patient.id)).map((patient) => patient.id); const allSelected = ids.length > 0 && ids.every((id) => selected.has(id)); setSelected((current) => { const next = new Set(current); ids.forEach((id) => allSelected ? next.delete(id) : next.add(id)); return next; }); }
  const invitationUrl = (id: string) => `${window.location.origin}/patient-access/invitations/${id}`;

  return <div><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold text-indigo-600">Synthetic linkage pilot</p><h1 className="mt-1 text-3xl font-bold">Patients</h1><p className="mt-2 text-content-secondary">Manage patient demographics and create access invitations individually, in a selected group, or for every eligible synthetic patient.</p></div><button onClick={onImportPatients} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white"><FileUp className="h-4 w-4" />Import patients</button></div>
    <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>Non-production consent workflow.</strong> Acceptance activates the identity link and 30-day access grant immediately. Delivery jobs are queued and deduplicated by recipient; external sending remains paused until a sender domain is configured.</div>
    <section className="mt-6 rounded-xl border border-stroke-subtle bg-surface-raised p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><h2 className="flex items-center gap-2 font-semibold"><KeyRound className="h-5 w-5 text-indigo-600" />Protected bulk actions</h2><p className="mt-1 text-sm text-content-secondary">Creating invitations requires fresh MFA.</p></div><form className="flex w-full gap-2 lg:w-auto" onSubmit={(event) => { event.preventDefault(); void verify(); }}><label className="sr-only" htmlFor="patient-access-mfa">Six-digit authenticator code</label><input id="patient-access-mfa" value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ''))} maxLength={6} inputMode="numeric" className="min-w-0 flex-1 rounded-lg border border-stroke-default px-3 py-2.5 text-center tracking-[.25em] lg:w-48" placeholder="000000" /><button disabled={busy === 'mfa'} className="rounded-lg border border-stroke-default px-4 text-sm font-semibold">Verify</button></form></div></section>
    {(error || message) && <div role={error ? 'alert' : 'status'} className={`mt-4 rounded-lg border p-3 text-sm ${error ? 'border-red-200 bg-red-50 text-red-700' : 'border-emerald-200 bg-emerald-50 text-emerald-800'}`}>{error || message}</div>}
    <section className="mt-6 overflow-hidden rounded-xl border border-stroke-subtle bg-surface-raised">
      <div className="flex flex-col gap-4 border-b border-stroke-subtle px-5 pt-4 sm:flex-row sm:items-end sm:justify-between"><div className="flex gap-6" role="tablist" aria-label="Patient access lists"><button role="tab" aria-selected={tab === 'patients'} onClick={() => setTab('patients')} className={`border-b-2 pb-3 text-sm font-semibold ${tab === 'patients' ? 'border-indigo-600 text-indigo-700' : 'border-transparent text-content-secondary'}`}>All patients <span className="ml-1 text-xs">{patients.length}</span></button><button role="tab" aria-selected={tab === 'invited'} onClick={() => setTab('invited')} className={`border-b-2 pb-3 text-sm font-semibold ${tab === 'invited' ? 'border-indigo-600 text-indigo-700' : 'border-transparent text-content-secondary'}`}>Invited <span className="ml-1 text-xs">{invitations.length}</span></button></div><button onClick={() => void load()} className="mb-3 flex items-center gap-2 text-sm font-semibold text-indigo-700"><RefreshCw className={`h-4 w-4 ${busy === 'load' ? 'animate-spin' : ''}`} />Refresh</button></div>
      <div className="flex flex-col gap-3 border-b border-stroke-subtle bg-surface-sunken px-5 py-4 lg:flex-row lg:items-center lg:justify-between"><label className="relative block lg:w-96"><span className="sr-only">Search list</span><Search className="absolute left-3 top-3 h-4 w-4 text-content-tertiary" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name, patient number, or email" className="w-full rounded-lg border border-stroke-default bg-white py-2.5 pl-9 pr-3 text-sm" /></label>{tab === 'patients' && <div className="flex flex-wrap items-center gap-2"><span className="mr-1 text-sm font-medium text-content-secondary">{selected.size} selected</span><button disabled={!selected.size || busy === 'create'} onClick={() => void createBulk(false)} className="flex items-center gap-2 rounded-lg border border-indigo-300 bg-white px-3 py-2 text-sm font-semibold text-indigo-700 disabled:opacity-50"><Send className="h-4 w-4" />Invite selected</button><button disabled={!eligiblePatients.length || busy === 'create'} onClick={() => window.confirm('Create invitations for every eligible synthetic roster patient? Existing pending invitations will be skipped.') && void createBulk(true)} className="flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy === 'create' ? <Loader2 className="h-4 w-4 animate-spin" /> : <Users className="h-4 w-4" />}Invite all eligible</button></div>}</div>
      {tab === 'invited' && <DeliveryJobs jobs={deliveryJobs} busy={busy} onUpdate={updateDelivery} />}
      <div className="overflow-x-auto">{tab === 'patients' ? <PatientTable patients={visiblePatients} selected={selected} eligibleIds={eligibleIds} invitationByPatient={invitationByPatient} onToggle={toggle} onTogglePage={togglePage} /> : <InvitationTable invitations={visibleInvitations} invitationUrl={invitationUrl} />}</div>
      {activeRows.length === 0 && <div className="p-10 text-center text-sm text-content-secondary"><Link2 className="mx-auto mb-3 h-6 w-6" />{tab === 'patients' ? 'No eligible roster patients match this search.' : 'No invitations match this search.'}</div>}
      {activeRows.length > 0 && <div className="flex items-center justify-between border-t border-stroke-subtle px-5 py-3 text-sm"><span className="text-content-secondary">{(page - 1) * PAGE_SIZE + 1}–{Math.min(page * PAGE_SIZE, activeRows.length)} of {activeRows.length}</span><div className="flex gap-2"><button disabled={page === 1} onClick={() => setPage((value) => value - 1)} className="rounded-lg border border-stroke-default px-3 py-1.5 font-semibold disabled:opacity-40">Previous</button><button disabled={page === totalPages} onClick={() => setPage((value) => value + 1)} className="rounded-lg border border-stroke-default px-3 py-1.5 font-semibold disabled:opacity-40">Next</button></div></div>}
    </section>
  </div>;
}

function PatientTable({ patients, selected, eligibleIds, invitationByPatient, onToggle, onTogglePage }: { patients: Patient[]; selected: Set<string>; eligibleIds: Set<string>; invitationByPatient: Map<string, Invitation>; onToggle: (id: string) => void; onTogglePage: () => void }) {
  const selectable = patients.filter((item) => eligibleIds.has(item.id));
  return <table className="w-full text-left text-sm"><thead className="border-b border-stroke-subtle bg-white text-xs uppercase tracking-wide text-content-tertiary"><tr><th className="w-12 px-5 py-3"><input aria-label="Select all eligible patients on this page" type="checkbox" checked={selectable.length > 0 && selectable.every((item) => selected.has(item.id))} onChange={onTogglePage} /></th><th className="px-3 py-3">Patient</th><th className="px-3 py-3">Patient number</th><th className="px-3 py-3">Email</th><th className="px-5 py-3">Access</th></tr></thead><tbody className="divide-y divide-stroke-subtle">{patients.map((patient) => { const invitation = invitationByPatient.get(patient.id); const eligible = eligibleIds.has(patient.id); const label = !patient.email ? 'Email required' : invitation?.status === 'accepted' ? 'Access active' : invitation?.status === 'pending' ? 'Invited' : 'Not invited'; return <tr key={patient.id} className={selected.has(patient.id) ? 'bg-indigo-50/60' : ''}><td className="px-5 py-3"><input aria-label={`Select ${patient.givenName} ${patient.familyName}`} type="checkbox" disabled={!eligible} checked={selected.has(patient.id)} onChange={() => onToggle(patient.id)} /></td><td className="px-3 py-3 font-semibold">{patient.familyName}, {patient.givenName}</td><td className="px-3 py-3 font-mono text-xs">{patient.organizationPatientNumber ?? '—'}</td><td className="px-3 py-3">{patient.email ?? <span className="text-content-tertiary">Not provided</span>}</td><td className="px-5 py-3"><span className={`rounded-md px-2 py-1 text-xs font-semibold ${label === 'Access active' ? 'bg-emerald-100 text-emerald-800' : label === 'Invited' ? 'bg-amber-100 text-amber-900' : label === 'Email required' ? 'bg-red-50 text-red-700' : 'bg-slate-100 text-slate-700'}`}>{label}</span></td></tr>; })}</tbody></table>;
}

function InvitationTable({ invitations, invitationUrl }: { invitations: Invitation[]; invitationUrl: (id: string) => string }) {
  const [copiedId, setCopiedId] = useState('');
  async function copy(item: Invitation) { await navigator.clipboard.writeText(invitationUrl(item.id)); setCopiedId(item.id); window.setTimeout(() => setCopiedId((current) => current === item.id ? '' : current), 2000); }
  return <table className="w-full text-left text-sm"><thead className="border-b border-stroke-subtle bg-white text-xs uppercase tracking-wide text-content-tertiary"><tr><th className="px-5 py-3">Patient</th><th className="px-3 py-3">Email</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Access period</th><th className="px-5 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-stroke-subtle">{invitations.map((item) => <tr key={item.id}><td className="px-5 py-3 font-semibold">{item.patient ? `${item.patient.family_name}, ${item.patient.given_name}` : 'Roster patient'}</td><td className="px-3 py-3">{item.email}</td><td className="px-3 py-3"><span className={`rounded-md px-2 py-1 text-xs font-semibold capitalize ${item.status === 'accepted' ? 'bg-emerald-100 text-emerald-800' : item.status === 'pending' ? 'bg-amber-100 text-amber-900' : 'bg-slate-100 text-slate-700'}`}>{item.status === 'accepted' ? 'Access active' : item.status}</span></td><td className="px-3 py-3 text-xs text-content-secondary">{item.status === 'accepted' ? `Through ${new Date(item.access_expires_at).toLocaleDateString()}` : item.status === 'pending' ? `Invite expires ${new Date(item.expires_at).toLocaleDateString()}` : `Lifecycle ended ${new Date(item.access_expires_at).toLocaleDateString()}`}</td><td className="px-5 py-3 text-right">{item.status === 'pending' ? <div className="flex justify-end gap-2"><button onClick={() => window.open(invitationUrl(item.id), '_blank', 'noopener,noreferrer')} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-semibold text-white"><ExternalLink className="h-4 w-4" />Open review</button><button onClick={() => void copy(item)} className="inline-flex items-center gap-2 rounded-lg border border-stroke-default px-3 py-2 text-sm font-semibold">{copiedId === item.id ? <Check className="h-4 w-4 text-emerald-600" /> : <Clipboard className="h-4 w-4" />}{copiedId === item.id ? 'Copied' : 'Copy link'}</button></div> : <span className="text-xs text-content-tertiary">No action</span>}</td></tr>)}</tbody></table>;
}

function DeliveryJobs({ jobs, busy, onUpdate }: { jobs: DeliveryJob[]; busy: string; onUpdate: (action: 'cancel-patient-access-delivery' | 'retry-patient-access-delivery', id: string) => void }) {
  if (!jobs.length) return null;
  return <div className="border-b border-stroke-subtle bg-white px-5 py-4"><h3 className="text-sm font-semibold">Delivery queue</h3><div className="mt-3 grid gap-2">{jobs.slice(0, 5).map((job) => <div key={job.id} className="flex flex-col gap-2 rounded-lg border border-stroke-subtle p-3 text-sm sm:flex-row sm:items-center sm:justify-between"><div><strong>{job.recipient_email}</strong><p className="mt-0.5 text-xs text-content-secondary">{job.invitation_count} invitation{job.invitation_count === 1 ? '' : 's'} · digest · {job.status}{job.attempt_count ? ` · ${job.attempt_count} attempts` : ''}</p>{job.last_error && <p className="mt-1 text-xs text-red-700">{job.last_error}</p>}</div><div className="flex gap-2">{job.status === 'queued' && <button disabled={busy === job.id} onClick={() => onUpdate('cancel-patient-access-delivery', job.id)} className="rounded-lg border border-stroke-default px-3 py-1.5 text-xs font-semibold">Cancel</button>}{(job.status === 'failed' || job.status === 'cancelled') && <button disabled={busy === job.id} onClick={() => onUpdate('retry-patient-access-delivery', job.id)} className="rounded-lg border border-indigo-300 px-3 py-1.5 text-xs font-semibold text-indigo-700">Retry</button>}</div></div>)}</div></div>;
}
