import { RefreshCw, Search, ShieldCheck } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabase';

interface AuditEvent { id: string; occurredAt: string; actorPrincipalId: string | null; action: string; targetType: string | null; targetRef: string | null; outcome: string; reason: string | null; requestId: string | null }

const readable = (value: string) => value.replace(/[._]/g, ' ');

export function ProviderAuditPanel({ providerAccountId }: { providerAccountId: string }) {
  const [events, setEvents] = useState<AuditEvent[]>([]); const [search, setSearch] = useState(''); const [outcome, setOutcome] = useState('all');
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); const { data, error: invokeError } = await supabase.functions.invoke('provider-admin-api', { body: { action: 'list-provider-audit-events', providerAccountId } }); if (invokeError) setError(data?.error ?? invokeError.message); else setEvents(data?.events ?? []); setLoading(false); }, [providerAccountId]);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => { const query = search.trim().toLowerCase(); return events.filter((event) => (outcome === 'all' || event.outcome === outcome) && (!query || `${event.action} ${event.targetType ?? ''} ${event.targetRef ?? ''} ${event.reason ?? ''} ${event.requestId ?? ''}`.toLowerCase().includes(query))); }, [events, search, outcome]);
  return <section className="mt-8 overflow-hidden rounded-xl border border-stroke-subtle bg-surface-raised"><div className="flex flex-col gap-4 border-b border-stroke-subtle px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-5 w-5 text-indigo-600" />Security activity</h2><p className="mt-1 text-sm text-content-secondary">Latest provider administration, access, delivery, and authorization events.</p></div><button onClick={() => void load()} className="flex items-center gap-2 text-sm font-semibold text-indigo-700"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></div><div className="flex flex-col gap-3 border-b border-stroke-subtle bg-surface-sunken px-5 py-4 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search security activity</span><Search className="absolute left-3 top-3 h-4 w-4 text-content-tertiary" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search action, target, reason, or request ID" className="w-full rounded-lg border border-stroke-default bg-white py-2.5 pl-9 pr-3 text-sm" /></label><label><span className="sr-only">Filter by outcome</span><select value={outcome} onChange={(event) => setOutcome(event.target.value)} className="w-full rounded-lg border border-stroke-default bg-white px-3 py-2.5 text-sm sm:w-44"><option value="all">All outcomes</option><option value="succeeded">Succeeded</option><option value="denied">Denied</option><option value="failed">Failed</option></select></label></div>{error ? <div role="alert" className="m-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div> : visible.length ? <div className="divide-y divide-stroke-subtle">{visible.slice(0, 50).map((event) => <article key={event.id} className="grid gap-2 px-5 py-4 text-sm lg:grid-cols-[180px_1fr_auto]"><time className="text-content-secondary" dateTime={event.occurredAt}>{new Date(event.occurredAt).toLocaleString()}</time><div><p className="font-semibold capitalize">{readable(event.action)}</p><p className="mt-1 text-xs text-content-secondary">{event.targetType ? readable(event.targetType) : 'Provider event'}{event.targetRef ? ` · ${event.targetRef}` : ''}{event.reason ? ` · ${event.reason}` : ''}</p>{event.requestId && <p className="mt-1 font-mono text-[11px] text-content-tertiary">Request {event.requestId}</p>}</div><span className={`self-start rounded-md px-2 py-1 text-xs font-semibold capitalize ${event.outcome === 'succeeded' ? 'bg-emerald-100 text-emerald-800' : event.outcome === 'denied' ? 'bg-amber-100 text-amber-900' : 'bg-red-50 text-red-700'}`}>{event.outcome}</span></article>)}</div> : <p className="p-8 text-center text-sm text-content-secondary">{loading ? 'Loading security activity…' : 'No security activity matches these filters.'}</p>}</section>;
}
